### ISSUE TITLE
Minor bug fixes & enhancements

### ISSUE THREAD

**Issue by gammaw** [mmmnmnm/lahmacun_rework#201]
- [x] Footer wrongly displays Soundcloud instead of Mixcloud
- [x] #204
- [x] Schedule display madness: https://github.com/mmmnmnm/lahmacun_rework/issues/195
- [x] News item refresh on home: https://github.com/mmmnmnm/lahmacun_rework/issues/194
- [x] Hyperlinks not preserved: https://github.com/mmmnmnm/lahmacun_rework/issues/193
- [x] Robustness checks: https://github.com/mmmnmnm/lahmacun_rework/milestone/4
- [x] stream volume slidert nem lehet az elején kattintani (átdolgozni a formát)
- [x] fooldalon arcsi, mashol archive
- [x] statikus scroll: jobb oldalon 5 pixeles fuggoleges sav. A footer, header nem megy ki a kepernyo szeleig
- [x] Arcsi player: logó legyen bekarikázott A
- [x] Home-on a "donate us" szöveg a képen linkeljen a Donate oldalra
- [x] Change menu ring to underline
- [x] Add 10 sec back/forward to arcsi player
- [x] Add DJ Citrom to Impressum

**Comment by baxgas** [comment]
@gammaw sorry, what did you agree with the logo, should it be replaced at all places, placeholder images or only at header?

**Comment by baxgas** [comment]
@gammaw please check 
https://github.com/mmmnmnm/lahmacun_rework/pull/196 
for this!  Hyperlinks not preserved: Hyperlinks not preserved when displaying WP data #193

**Comment by baxgas** [comment]
@gammaw for this issue there is this stuck PR
 Robustness checks: https://github.com/mmmnmnm/lahmacun_rework/milestone/4
PR ---> https://github.com/mmmnmnm/lahmacun_rework/pull/160
